global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Linq.Expressions;
global using System.Reflection;
global using System.Runtime.CompilerServices;
global using MetaProgramming;
global using Microsoft.AspNetCore.Builder;
global using Microsoft.AspNetCore.Http;
global using Microsoft.Extensions.DependencyInjection;
global using QueryPredicates = System.Collections.Generic.Dictionary<string, System.Func<string, System.Func<MetaProgramming.Vector3d, bool>>>;
